version: '3.9'
services:
  backend:
    build: 
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=@DATABASE_URL
    volumes:
      - ./backend:/src/app
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    ports:
      - "8081:8081"
    depends_on:
      - backend

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
